#!/bin/bash
#    .---------- constant part!
#    vvvv vvvv-- the code from above
GREEN='\033[0;32m'
NC='\033[0m' # No Color


GIT_WORK_TREE=/home/react-projects/latin_squares git checkout daleprogress -f
echo -e "${GREEN} git checkout complete ${NC}"
cd /home/react-projects/latin_squares/backend/sudoku
echo -e "${GREEN} print working directory ${NC}"
pwd
echo -e "${GREEN}going to pipenv ${NC}"
pipenv install
cd /home/react-projects/latin_squares/frontend
echo -e "${GREEN} print working directory ${NC}"
pwd
npm install  
npm run build
echo -e "${GREEN} react build complete ${NC}"
echo -e "${GREEN} deploying to site ${NC}"
cp -r /home/react-projects/latin_squares/frontend/build/* /var/www/html/sudokuapp/sudokuapp/
echo -e "${GREEN} restarting nginx${NC}"
sudo systemctl stop nginx
sudo systemctl start nginx
echo -e "${GREEN} restarting gunicorn ${NC}"
sudo supervisorctl restart sudoku_gunicorn
